---
# This Playbook would deploy everything
- hosts:
    - "*-networked"
    - "*-controller"
  roles:
    - common

- hosts: db120-networked
  roles:
    - networked

- hosts: db120-lan
  roles:
    - lan_device

- hosts: db120-wan
  roles:
    - wan_device

- hosts: db120-controller
  roles:
    - controller
#- include: init_a_device.yml hosts_to_initialize=all
