- name: copy over command wrappers
  copy:
    src: "{{ item }}"
    dest: "/usr/bin"
    owner: root
    group: root
    mode: "0744"
  become: yes
  with_fileglob:
    - './setup_lan'
    - './start_lan_client'
    - './stop_lan_client'

- name: copy over default route
  copy:
    src: "{{ item }}"
    dest: "/etc/network/if-up.d/"
    owner: root
    group: root
    mode: "0755"
  become: yes
  with_fileglob:
    - './set_default_local_area_route'

- name: add lan init to rc.local
  lineinfile:
    dest: /etc/rc.local
    state: present
    insertbefore: '^exit 0'
    line: '/usr/bin/setup_lan'
  become: yes
