- name: copy over command wrappers
  copy:
    src: "{{ item }}"
    dest: "/etc"
    owner: root
    group: root
    mode: "0744"
  become: yes
  with_fileglob:
    - './setup_lan'

- name: add lan init to rc.local
  lineinfile:
    dest: /etc/rc.local
    state: present
    insertbefore: '^exit 0'
    line: '/usr/bin/setup_lan'
  become: yes
